<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>b2114e49-be37-4834-ac5a-58750390fcef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Authentication\Authentication.API\Authentication.API.csproj" />
  </ItemGroup>

</Project>
